//! Autogenerated weights for pallet_voting
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2023-06-16, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `runner-e8ezs4ez-project-145-concurrent-0`, CPU: `Intel(R) Xeon(R) CPU @ 2.60GHz`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

// Executed Command:
// ./target/production/substrate
// benchmark
// pallet
// --chain=dev
// --steps=50
// --repeat=20
// --pallet=pallet_voting
// --extrinsic=*
// --execution=wasm
// --wasm-execution=compiled
// --heap-pages=4096
// --output=./pallets/voting/src/weights.rs
// --template=./.maintain/frame-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for pallet_voting.
pub trait WeightInfo {
    fn create_proposal() -> Weight;
    fn vote() -> Weight;
    fn end_proposal() -> Weight;
    fn cancel_proposal() -> Weight;
}

/// Weights for pallet_voting using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
    /// Storage: Voting NextProposalId (r:1 w:1)
    /// Proof: Voting NextProposalId (max_values: Some(1), max_size: Some(4), added: 499, mode: MaxEncodedLen)
    /// Storage: Voting Proposals (r:0 w:1)
    /// Proof: Voting Proposals (max_values: None, max_size: Some(1000), added: 3475, mode: MaxEncodedLen)
    fn create_proposal() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `76`
        //  Estimated: `1489`
        // Minimum execution time: 15_000_000 picoseconds.
        Weight::from_parts(16_000_000, 1489)
            .saturating_add(T::DbWeight::get().reads(1_u64))
            .saturating_add(T::DbWeight::get().writes(2_u64))
    }

    /// Storage: Voting Proposals (r:1 w:0)
    /// Proof: Voting Proposals (max_values: None, max_size: Some(1000), added: 3475, mode: MaxEncodedLen)
    /// Storage: System Number (r:1 w:0)
    /// Proof: System Number (max_values: Some(1), max_size: Some(4), added: 499, mode: MaxEncodedLen)
    /// Storage: Voting Votes (r:1 w:1)
    /// Proof: Voting Votes (max_values: None, max_size: Some(100), added: 2575, mode: MaxEncodedLen)
    /// Storage: Voting VoteResults (r:1 w:1)
    /// Proof: Voting VoteResults (max_values: None, max_size: Some(8), added: 2483, mode: MaxEncodedLen)
    fn vote() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `200`
        //  Estimated: `4465`
        // Minimum execution time: 25_000_000 picoseconds.
        Weight::from_parts(26_000_000, 4465)
            .saturating_add(T::DbWeight::get().reads(4_u64))
            .saturating_add(T::DbWeight::get().writes(2_u64))
    }

    /// Storage: Voting Proposals (r:1 w:1)
    /// Proof: Voting Proposals (max_values: None, max_size: Some(1000), added: 3475, mode: MaxEncodedLen)
    /// Storage: System Number (r:1 w:0)
    /// Proof: System Number (max_values: Some(1), max_size: Some(4), added: 499, mode: MaxEncodedLen)
    /// Storage: Voting VoteResults (r:10 w:0)
    /// Proof: Voting VoteResults (max_values: None, max_size: Some(8), added: 2483, mode: MaxEncodedLen)
    fn end_proposal() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `300`
        //  Estimated: `25820`
        // Minimum execution time: 35_000_000 picoseconds.
        Weight::from_parts(36_000_000, 25820)
            .saturating_add(T::DbWeight::get().reads(12_u64))
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }

    /// Storage: Voting Proposals (r:1 w:1)
    /// Proof: Voting Proposals (max_values: None, max_size: Some(1000), added: 3475, mode: MaxEncodedLen)
    fn cancel_proposal() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `200`
        //  Estimated: `3465`
        // Minimum execution time: 20_000_000 picoseconds.
        Weight::from_parts(21_000_000, 3465)
            .saturating_add(T::DbWeight::get().reads(1_u64))
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }
}

// For backwards compatibility and tests
impl WeightInfo for () {
    fn create_proposal() -> Weight {
        Weight::from_parts(16_000_000, 1489)
            .saturating_add(RocksDbWeight::get().reads(1_u64))
            .saturating_add(RocksDbWeight::get().writes(2_u64))
    }

    fn vote() -> Weight {
        Weight::from_parts(26_000_000, 4465)
            .saturating_add(RocksDbWeight::get().reads(4_u64))
            .saturating_add(RocksDbWeight::get().writes(2_u64))
    }

    fn end_proposal() -> Weight {
        Weight::from_parts(36_000_000, 25820)
            .saturating_add(RocksDbWeight::get().reads(12_u64))
            .saturating_add(RocksDbWeight::get().writes(1_u64))
    }

    fn cancel_proposal() -> Weight {
        Weight::from_parts(21_000_000, 3465)
            .saturating_add(RocksDbWeight::get().reads(1_u64))
            .saturating_add(RocksDbWeight::get().writes(1_u64))
    }
}