//! Autogenerated weights for pallet_asset_registry
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2023-06-16, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `runner-e8ezs4ez-project-145-concurrent-0`, CPU: `Intel(R) Xeon(R) CPU @ 2.60GHz`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

// Executed Command:
// ./target/production/substrate
// benchmark
// pallet
// --chain=dev
// --steps=50
// --repeat=20
// --pallet=pallet_asset_registry
// --extrinsic=*
// --execution=wasm
// --wasm-execution=compiled
// --heap-pages=4096
// --output=./pallets/asset-registry/src/weights.rs
// --template=./.maintain/frame-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for pallet_asset_registry.
pub trait WeightInfo {
    fn register_asset() -> Weight;
    fn approve_asset() -> Weight;
    fn reject_asset() -> Weight;
    fn suspend_asset() -> Weight;
    fn update_asset_metadata() -> Weight;
    fn transfer_ownership() -> Weight;
}

/// Weights for pallet_asset_registry using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
    /// Storage: AssetRegistry NextAssetId (r:1 w:1)
    /// Proof: AssetRegistry NextAssetId (max_values: Some(1), max_size: Some(4), added: 499, mode: MaxEncodedLen)
    /// Storage: AssetRegistry AssetBySymbol (r:1 w:1)
    /// Proof: AssetRegistry AssetBySymbol (max_values: None, max_size: Some(100), added: 2575, mode: MaxEncodedLen)
    /// Storage: AssetRegistry AssetCountByOwner (r:1 w:1)
    /// Proof: AssetRegistry AssetCountByOwner (max_values: None, max_size: Some(36), added: 2511, mode: MaxEncodedLen)
    /// Storage: AssetRegistry Assets (r:0 w:1)
    /// Proof: AssetRegistry Assets (max_values: None, max_size: Some(2000), added: 4475, mode: MaxEncodedLen)
    /// Storage: AssetRegistry AssetsByOwner (r:0 w:1)
    /// Proof: AssetRegistry AssetsByOwner (max_values: None, max_size: Some(36), added: 2511, mode: MaxEncodedLen)
    fn register_asset() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `76`
        //  Estimated: `3565`
        // Minimum execution time: 25_000_000 picoseconds.
        Weight::from_parts(26_000_000, 3565)
            .saturating_add(T::DbWeight::get().reads(3_u64))
            .saturating_add(T::DbWeight::get().writes(5_u64))
    }

    /// Storage: AssetRegistry Assets (r:1 w:1)
    /// Proof: AssetRegistry Assets (max_values: None, max_size: Some(2000), added: 4475, mode: MaxEncodedLen)
    fn approve_asset() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `200`
        //  Estimated: `4465`
        // Minimum execution time: 15_000_000 picoseconds.
        Weight::from_parts(16_000_000, 4465)
            .saturating_add(T::DbWeight::get().reads(1_u64))
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }

    /// Storage: AssetRegistry Assets (r:1 w:1)
    /// Proof: AssetRegistry Assets (max_values: None, max_size: Some(2000), added: 4475, mode: MaxEncodedLen)
    fn reject_asset() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `200`
        //  Estimated: `4465`
        // Minimum execution time: 15_000_000 picoseconds.
        Weight::from_parts(16_000_000, 4465)
            .saturating_add(T::DbWeight::get().reads(1_u64))
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }

    /// Storage: AssetRegistry Assets (r:1 w:1)
    /// Proof: AssetRegistry Assets (max_values: None, max_size: Some(2000), added: 4475, mode: MaxEncodedLen)
    fn suspend_asset() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `200`
        //  Estimated: `4465`
        // Minimum execution time: 15_000_000 picoseconds.
        Weight::from_parts(16_000_000, 4465)
            .saturating_add(T::DbWeight::get().reads(1_u64))
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }

    /// Storage: AssetRegistry Assets (r:1 w:1)
    /// Proof: AssetRegistry Assets (max_values: None, max_size: Some(2000), added: 4475, mode: MaxEncodedLen)
    fn update_asset_metadata() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `200`
        //  Estimated: `4465`
        // Minimum execution time: 15_000_000 picoseconds.
        Weight::from_parts(16_000_000, 4465)
            .saturating_add(T::DbWeight::get().reads(1_u64))
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }

    /// Storage: AssetRegistry Assets (r:1 w:1)
    /// Proof: AssetRegistry Assets (max_values: None, max_size: Some(2000), added: 4475, mode: MaxEncodedLen)
    /// Storage: AssetRegistry AssetCountByOwner (r:2 w:2)
    /// Proof: AssetRegistry AssetCountByOwner (max_values: None, max_size: Some(36), added: 2511, mode: MaxEncodedLen)
    /// Storage: AssetRegistry AssetsByOwner (r:0 w:2)
    /// Proof: AssetRegistry AssetsByOwner (max_values: None, max_size: Some(36), added: 2511, mode: MaxEncodedLen)
    fn transfer_ownership() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `300`
        //  Estimated: `6012`
        // Minimum execution time: 30_000_000 picoseconds.
        Weight::from_parts(31_000_000, 6012)
            .saturating_add(T::DbWeight::get().reads(3_u64))
            .saturating_add(T::DbWeight::get().writes(5_u64))
    }
}

// For backwards compatibility and tests
impl WeightInfo for () {
    fn register_asset() -> Weight {
        Weight::from_parts(26_000_000, 3565)
            .saturating_add(RocksDbWeight::get().reads(3_u64))
            .saturating_add(RocksDbWeight::get().writes(5_u64))
    }

    fn approve_asset() -> Weight {
        Weight::from_parts(16_000_000, 4465)
            .saturating_add(RocksDbWeight::get().reads(1_u64))
            .saturating_add(RocksDbWeight::get().writes(1_u64))
    }

    fn reject_asset() -> Weight {
        Weight::from_parts(16_000_000, 4465)
            .saturating_add(RocksDbWeight::get().reads(1_u64))
            .saturating_add(RocksDbWeight::get().writes(1_u64))
    }

    fn suspend_asset() -> Weight {
        Weight::from_parts(16_000_000, 4465)
            .saturating_add(RocksDbWeight::get().reads(1_u64))
            .saturating_add(RocksDbWeight::get().writes(1_u64))
    }

    fn update_asset_metadata() -> Weight {
        Weight::from_parts(16_000_000, 4465)
            .saturating_add(RocksDbWeight::get().reads(1_u64))
            .saturating_add(RocksDbWeight::get().writes(1_u64))
    }

    fn transfer_ownership() -> Weight {
        Weight::from_parts(31_000_000, 6012)
            .saturating_add(RocksDbWeight::get().reads(3_u64))
            .saturating_add(RocksDbWeight::get().writes(5_u64))
    }
}